-- Create table topics
CREATE TABLE IF NOT EXISTS topics (
    id VARCHAR(30) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);